name: clean_eeg
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pyedflib>=0.1.42
      - edfio==0.4.9
      - lunapi==1.2.3
      - numpy>=2.3.2
      - mne==1.10.1
      - pytest
